# POST http://localhost:8080/register
# Content-Type: application/json

# {
#   "username": "shivangi1231",
#   "password": "test123456",
#   "email": "shivangii@example.com",
#   "name": "Shivangi1"
# }

# POST http://localhost:8080/login HTTP/1.1
# Content-Type: application/json

# {
#   "email":"shivangii@example.com",     
#   "password":"test123456"
# }

GET  http://localhost:8080/get_user_and_profile 
Content-Type: application/json

{
  "token":"a046926a268c1d058e096c31b8de3abc84e16dc4635bd9cef3aee930faeada21"
}